{{- if .Values.config }}
---
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}-config
data:
  {{- range .Values.config }}
  {{ .name }}: {{ .file }}
  {{- end}}
{{- end}}

